### ISSUE TITLE
Chats on XMTP.chat aren't sorted reverse chronologically

### ISSUE THREAD

**Issue by prashantpbagga** [xmtp/example-chat-react#103]
**Summary**
Chats on XMTP.chat aren't sorted reverse chronologically.

**Steps to reproduce**
1. Send/receive messages from 5+ wallets.
2. Check sorting of the messages.

**Expected behavior**
The most recent chats should be displayed at the top and the oldest at the bottom in the messages feed. 

**Actual behavior**
Chats are randomly ordered and not sorted reverse chronologically. 

**Attachments**

<img width="333" alt="image" src="https://user-images.githubusercontent.com/80154899/190216541-00535954-3008-4814-a225-ecb4cbc9d5d4.png">

**Environment**
 - OS version: MacOS Monterey 12.3.1
 - Browser version: Google Chrome 105.0.5195.125
 - `xmtp-js` version (if known): -
 - Deployment URL (if applicable): -

**Comment by saulmc** [comment]
Resolved by https://github.com/xmtp/example-chat-react/commit/a4d7329299a67d4c9293e625540c8828bf6d9c91

**Comment by prashantpbagga** [comment]
🤜 🤛
