### ISSUE TITLE
Bug: Extra space below message input field

### ISSUE THREAD

**Issue by saulmc** [xmtp/example-chat-react#147]
## Describe the bug

There is now some extra space below the message input field, which as designed and in previous versions of the app was anchored to the bottom of the viewport.

## Steps to Reproduce

1. Go to xmtp.chat
2. Connect wallet and sign to enable
3. See that the message composer bar containing "Type something..." is no longer aligned with the bottom of the viewport

## Expected behavior

The message composer bar should be aligned with the bottom of the viewport.

## Screenshots

|Expected|Actual|
|-|-|
|<img width="1492" alt="CleanShot 2022-12-01 at 22 11 02@2x" src="https://user-images.githubusercontent.com/510695/205227583-9a6577fc-7c9b-4ad3-8fb6-8e90b9a8c063.png">|<img width="1492" alt="CleanShot 2022-12-01 at 22 16 00@2x" src="https://user-images.githubusercontent.com/510695/205227813-994e6f54-3495-44f4-9089-25b4cb638a72.png">|

## Additional context

Looks like it might be a sizing issue with the parent container.

<img width="1000" alt="CleanShot 2022-12-01 at 22 09 07@2x" src="https://user-images.githubusercontent.com/510695/205228051-34195474-c727-4a03-8787-bc7fa0a652cc.png">

### Desktop

- OS & Version: macOS 13.0
- Browser & Version: Arc 0.77.2

**Comment by galligan** [comment]
Just saw this one too. It's not just that it's extra space—it seems that the Tailwind class h-screen is not actually calculating properly for some reason, as the space changes as the window gets smaller, and at some point the typing bar is lost entirely.

Here's a video showing this behavior:
https://shots.xmtp.com/2tNv1J

cc @bhavya2611
