### ISSUE TITLE
Bug:  Excessive Errors in the Console

### ISSUE THREAD

**Issue by jazzz** [xmtp/example-chat-react#172]
## Describe the bug

Excessive errors in the devtools console. First reported by @prashantpbagga 

## Steps to Reproduce

1. Go to 'vercel.xmtp.com'
2. Login in with your Blockchain account
3. Inspect

Occurs after login, without any further user action.

## Expected behavior

Not lots of errors.

## Screenshots

<img width="1602" alt="image" src="https://user-images.githubusercontent.com/473256/211407435-7c4f233e-118b-4632-a8bb-ac8f128901df.png">

<img width="635" alt="image" src="https://user-images.githubusercontent.com/473256/211406824-0055bf71-eb86-4a97-a3b1-bf73e52dca87.png">
<img width="973" alt="Screenshot 2023-01-09 at 12 33 08 PM" src="https://user-images.githubusercontent.com/473256/211406843-fc8776ef-c34e-46bd-8dba-4cddd5beea61.png">

### Desktop

Please complete the following information if you think it is relevant to the bug:

- OS & Version: [e.g. macOS 13.0.1]
- Browser & Version: [Brave 1.46.140]

**Comment by michaelx11** [comment]
Steps to repro addition: attempt to log in with WalletConnect to trigger the issue. Metamask login worked fine for me.

**Comment by michaelx11** [comment]
@snormore - points out that we're likely not using the right InfuraID. He's looking into that work thread now.

I'm looking into why we're getting so many requests in the first place if there's a 800ms retry timeout. I believe we're invoking this effect https://github.com/xmtp/example-chat-react/blob/main/hooks/useWalletProvider.tsx#L106-L107 to initialize a walletConnect provider 12 times in quick succession when a user connects with WalletConnect.

See "invoking effect" log line in this screenshot. These 12 initializations match the spamming behavior which is 10-12 requests punctuated by a short 800ms delay

<img width="545" alt="Screen Shot 2023-01-09 at 1 51 07 PM" src="https://user-images.githubusercontent.com/1329295/211416108-bdbd17cb-5d6e-450a-b772-48251d071801.png">

**Comment by michaelx11** [comment]
I'm tracing the hooks a bit, still not exactly sure of why we're getting multiple provider initializations but here are some clues:

In a release build (xmtp.chat) we see 6 duplicate web3Modal HTML tags. In a dev build we see 12 (React doubles some hooks in dev). It looks like multiple `provider` instances are created independently and all will separately retry their connections, or poll.

Screenshots from a local build:
<img width="859" alt="Screen Shot 2023-01-09 at 2 10 07 PM" src="https://user-images.githubusercontent.com/1329295/211419136-90db9544-aa33-4116-83d6-b79adf22dfbc.png">
<img width="571" alt="Screen Shot 2023-01-09 at 2 10 51 PM" src="https://user-images.githubusercontent.com/1329295/211419148-81bd9381-8c43-4d16-9e58-4c6dcaca956a.png">

**Comment by elisealix22** [comment]
I'm able to reproduce this! Looks like this is causing ENS resolution to fail as well. We'll prioritize.

**Comment by neekolas** [comment]
At least part of the problem is that we are giving our Infura API key away to the public in our code, who can then abuse it and eat up our rate limit. 

We should use a separate key with a paid account for our deployed versions of our 1P apps. We can lock the key to our 1P domains to avoid people stealing that one.
