### ISSUE TITLE
Messages from previous session persists after disconnecting wallet.

### ISSUE THREAD

**Issue by jazzz** [xmtp/example-chat-react#91]
## Summary
When using the 'Disconnect Wallet' button messages from the previous login are shown in the conversation

## Environment
Browser: Brave 1.40.113, Firefox 103.0.2
OS: OSX 12.4
Reproducibility: Consistently across different browsers, tested against https://chat-3hb.pages.dev/

## Steps to Reproduce
1. Log into the Example App with WalletA
2. Find a conversation with with message history (Note Recipient as Recipient1)
3. Log out using 'Disconnect Wallet'
4. Log into the Example App with a new WalletB
5. Enter Recipient1 into the address bar

## Result
Messages from WalletA load into the conversation between WalletB and Recipient1

## Expected Result
Old Messages from WalletA are not visible to WalletB

## Notes
- Example: Previous session was logged in as 0xf8e6.......
![BugExample](https://user-images.githubusercontent.com/473256/185246917-66d60bd3-804e-4c73-a6fc-4606df4bbb54.png)

- Reloading the page removed the old messages

**Comment by neekolas** [comment]
This seems like another good starter task for Bhavya
